#pragma once
#include <map>
#include <iostream>
#include "analysis.h"
#include "merge.h"
#include "filter.h"

class Kpool {

    public:
        // Command-line arguments are stored as variables to be used by analysis-specific parsers
        int argc;
        char** argv;

        // Store the type of analysis to run detected from the command-line arguments in the RadSex constructor
        Analysis analysis;

        // Store all parameter values and properties inside a list.
        Parameters parameters;

        // Define all analyses
        // Analysis constructor: Analysis(name, description, parameters, function ref)
        std::map<std::string, Analysis> analyses { {"merge",
                                                    Analysis("merge",
                                                             "Merge a male kmers table and a female kmers table generated by Jellyfish into a single table.",
                                                             std::vector<std::string> {"male_table",
                                                                                       "female_table",
                                                                                       "output_file"},
                                                             merge)},
                                                   {"filter",
                                                    Analysis("filter",
                                                             "Filter a merged table to find sex-specific kmers",
                                                             std::vector<std::string> {"merged_table",
                                                                                       "output_file",
                                                                                       "heterogametic_sex",
                                                                                       "min_hetero_cov",
                                                                                       "max_hetero_cov",
                                                                                       "max_homo_cov"},
                                                             filter)}
                                                 };

        // In the constructor, the type of analysis is detected and all analysis objects are initialized
        Kpool(int& argc, char** argv);

        // Parse command-line arguments
        void parse();

        // Runs the selected analysis
        void run();

        // Print the general radsex usage
        void usage();

        // Print usage for the specified analysis
        void usage(Analysis analysis);

};
